#!/bin/bash
#
# Scaffold and Push Script - Phase 3 Integration
# Combines project generation with automated GitHub push
#

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Logging
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_section() { echo -e "${CYAN}$1${NC}"; }

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$(cd "$SCRIPT_DIR/../templates" && pwd)"

# Help
show_help() {
    cat << 'HELP'
Usage: scaffold-and-push.sh [OPTIONS] <project-name> <template>

Generate a project and optionally push to GitHub.

Arguments:
  project-name    Name for the new project (and GitHub repo)
  template        Template to use: nextjs-fullstack | express-react

Options:
  --github        Push to GitHub after generation
  --private       Create private GitHub repo (default: public)
  --description   Repository description
  --output-dir    Output directory (default: current directory)
  --dry-run       Show what would be done without executing
  --help          Show this help

Environment Variables:
  GITHUB_TOKEN    GitHub personal access token (required for --github)

Examples:
  scaffold-and-push.sh my-app nextjs-fullstack
  scaffold-and-push.sh --github my-app nextjs-fullstack
  scaffold-and-push.sh --github --private my-app express-react

HELP
}

# Parse arguments
PROJECT_NAME=""
TEMPLATE=""
USE_GITHUB=false
VISIBILITY="public"
DESCRIPTION=""
OUTPUT_DIR="."
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --github)
            USE_GITHUB=true
            shift
            ;;
        --private)
            VISIBILITY="private"
            shift
            ;;
        --description)
            DESCRIPTION="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            show_help
            exit 0
            ;;
        -*)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [[ -z "$PROJECT_NAME" ]]; then
                PROJECT_NAME="$1"
            elif [[ -z "$TEMPLATE" ]]; then
                TEMPLATE="$1"
            else
                log_error "Too many arguments"
                show_help
                exit 1
            fi
            shift
            ;;
    esac
done

# Validate
if [[ -z "$PROJECT_NAME" ]] || [[ -z "$TEMPLATE" ]]; then
    log_error "Project name and template are required"
    show_help
    exit 1
fi

# Validate template
if [[ ! -d "$TEMPLATES_DIR/$TEMPLATE" ]]; then
    log_error "Template not found: $TEMPLATE"
    log_info "Available templates:"
    ls -1 "$TEMPLATES_DIR" 2>/dev/null | while read -r t; do
        log_info "  - $t"
    done
    exit 1
fi

# Check GitHub prerequisites
if [[ "$USE_GITHUB" == true ]]; then
    if [[ -z "${GITHUB_TOKEN:-}" ]]; then
        log_error "GITHUB_TOKEN is required for --github"
        log_info "Set it with: export GITHUB_TOKEN=your_token"
        exit 1
    fi
fi

# Set default description
if [[ -z "$DESCRIPTION" ]]; then
    case $TEMPLATE in
        nextjs-fullstack)
            DESCRIPTION="Next.js full-stack application generated by OpenClaw"
            ;;
        express-react)
            DESCRIPTION="Express + React application generated by OpenClaw"
            ;;
        *)
            DESCRIPTION="Project generated by OpenClaw Scaffolding Engine"
            ;;
    esac
fi

# Resolve output directory
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"
PROJECT_PATH="$OUTPUT_DIR/$PROJECT_NAME"

# Print summary
log_section "========================================"
log_section "  OpenClaw Scaffolding Engine"
log_section "========================================"
echo ""
log_info "Project Name: $PROJECT_NAME"
log_info "Template: $TEMPLATE"
log_info "Output Directory: $OUTPUT_DIR"
log_info "GitHub Push: $USE_GITHUB"
if [[ "$USE_GITHUB" == true ]]; then
    log_info "Repository Visibility: $VISIBILITY"
fi
if [[ "$DRY_RUN" == true ]]; then
    log_warn "DRY RUN MODE"
fi
echo ""

# Phase 1: Generate Project
log_section "Phase 1: Project Generation"
log_info "Generating project from template..."

if [[ "$DRY_RUN" == true ]]; then
    log_info "[DRY-RUN] Would create project at: $PROJECT_PATH"
else
    # Create output directory if needed
    mkdir -p "$OUTPUT_DIR"
    
    # Check if project already exists
    if [[ -d "$PROJECT_PATH" ]]; then
        log_warn "Project directory already exists: $PROJECT_PATH"
        read -p "Overwrite? (y/N): " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            log_info "Cancelled"
            exit 0
        fi
        rm -rf "$PROJECT_PATH"
    fi
    
    # Copy template
    mkdir -p "$PROJECT_PATH"
    
    # Use find to copy all files including hidden ones
    find "$TEMPLATES_DIR/$TEMPLATE" -mindepth 1 -maxdepth 1 -exec cp -r {} "$PROJECT_PATH/" \;
    
    # Update package.json with project name
    if [[ -f "$PROJECT_PATH/package.json" ]]; then
        # Handle both single package and workspace
        if [[ -f "$PROJECT_PATH/server/package.json" ]]; then
            # Express+React workspace
            jq --arg name "${PROJECT_NAME}-server" '.name = $name' "$PROJECT_PATH/server/package.json" > "$PROJECT_PATH/server/package.json.tmp" && \
                mv "$PROJECT_PATH/server/package.json.tmp" "$PROJECT_PATH/server/package.json"
            jq --arg name "${PROJECT_NAME}-client" '.name = $name' "$PROJECT_PATH/client/package.json" > "$PROJECT_PATH/client/package.json.tmp" && \
                mv "$PROJECT_PATH/client/package.json.tmp" "$PROJECT_PATH/client/package.json"
            jq --arg name "$PROJECT_NAME" '.name = $name' "$PROJECT_PATH/package.json" > "$PROJECT_PATH/package.json.tmp" && \
                mv "$PROJECT_PATH/package.json.tmp" "$PROJECT_PATH/package.json"
        else
            # Single package
            jq --arg name "$PROJECT_NAME" '.name = $name' "$PROJECT_PATH/package.json" > "$PROJECT_PATH/package.json.tmp" && \
                mv "$PROJECT_PATH/package.json.tmp" "$PROJECT_PATH/package.json"
        fi
    fi
    
    log_success "Project generated: $PROJECT_PATH"
fi

# Phase 2: Install Dependencies
log_section "Phase 2: Dependency Installation"

if [[ "$DRY_RUN" == true ]]; then
    log_info "[DRY-RUN] Would run npm install"
else
    cd "$PROJECT_PATH"
    
    log_info "Installing dependencies (this may take a few minutes)..."
    if npm install --silent > /tmp/npm-install.log 2>&1; then
        log_success "Dependencies installed"
    else
        log_error "Failed to install dependencies"
        log_info "Check /tmp/npm-install.log for details"
        exit 1
    fi
fi

# Phase 3: Quality Gates
log_section "Phase 3: Quality Validation"

if [[ "$DRY_RUN" == true ]]; then
    log_info "[DRY-RUN] Would run quality checks"
else
    cd "$PROJECT_PATH"
    
    quality_passed=true
    quality_score=0
    
    # TypeScript check
    log_info "Running TypeScript check..."
    if [[ -f "tsconfig.json" ]]; then
        if npx tsc --noEmit > /tmp/tsc.log 2>&1; then
            log_success "TypeScript: PASS"
            ((quality_score+=2))
        else
            log_error "TypeScript: FAIL"
            quality_passed=false
        fi
    else
        log_warn "No tsconfig.json found, skipping TypeScript check"
    fi
    
    # For workspace projects, check both
    if [[ -d "server" ]] && [[ -d "client" ]]; then
        cd server
        if npx tsc --noEmit > /tmp/tsc-server.log 2>&1; then
            log_success "Server TypeScript: PASS"
            ((quality_score+=1))
        else
            log_error "Server TypeScript: FAIL"
            quality_passed=false
        fi
        cd ../client
        if npx tsc --noEmit > /tmp/tsc-client.log 2>&1; then
            log_success "Client TypeScript: PASS"
            ((quality_score+=1))
        else
            log_error "Client TypeScript: FAIL"
            quality_passed=false
        fi
        cd ..
    fi
    
    # ESLint check
    log_info "Running ESLint..."
    if [[ -f ".eslintrc.json" ]] || [[ -f ".eslintrc.js" ]]; then
        if npx eslint src --ext .ts,.tsx --max-warnings 0 > /tmp/eslint.log 2>&1; then
            log_success "ESLint: PASS"
            ((quality_score+=2))
        else
            log_error "ESLint: FAIL"
            quality_passed=false
        fi
    else
        log_warn "No ESLint config found, skipping"
    fi
    
    # Build check
    log_info "Running build..."
    if npm run build > /tmp/build.log 2>&1; then
        log_success "Build: PASS"
        ((quality_score+=2))
    else
        log_error "Build: FAIL"
        quality_passed=false
    fi
    
    # Structure check
    log_info "Checking project structure..."
    if [[ -d "src" ]] || [[ -d "client/src" ]]; then
        log_success "Structure: PASS"
        ((quality_score+=2))
    else
        log_error "Structure: FAIL"
        quality_passed=false
    fi
    
    # Dependencies check
    if [[ -d "node_modules" ]]; then
        log_success "Dependencies: PASS"
        ((quality_score+=2))
    else
        log_error "Dependencies: FAIL"
        quality_passed=false
    fi
    
    log_section ""
    log_section "Quality Score: $quality_score/10"
    
    if [[ "$quality_passed" == true ]]; then
        log_success "All quality gates passed!"
    else
        log_warn "Some quality checks failed"
    fi
fi

# Phase 4: GitHub Push (if requested)
if [[ "$USE_GITHUB" == true ]]; then
    log_section "Phase 4: GitHub Integration"
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would push to GitHub"
    else
        log_info "Pushing to GitHub..."
        
        export GITHUB_REPO_VISIBILITY="$VISIBILITY"
        
        if "$SCRIPT_DIR/github-push.sh" --description "$DESCRIPTION" "$PROJECT_PATH" "$PROJECT_NAME"; then
            log_success "GitHub push completed!"
        else
            log_error "GitHub push failed"
            exit 1
        fi
    fi
fi

# Final Summary
log_section ""
log_section "========================================"
log_section "  Scaffolding Complete!"
log_section "========================================"
echo ""
log_success "Project: $PROJECT_NAME"
log_success "Location: $PROJECT_PATH"
log_success "Template: $TEMPLATE"

if [[ "$USE_GITHUB" == true ]] && [[ "$DRY_RUN" != true ]]; then
    GITHUB_USERNAME=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/user 2>/dev/null | grep -o '"login": "[^"]*"' | cut -d'"' -f4 || echo "username")
    log_success "Repository: https://github.com/$GITHUB_USERNAME/$PROJECT_NAME"
fi

echo ""
log_info "Next steps:"
log_info "  cd $PROJECT_PATH"
log_info "  npm run dev"
echo ""

exit 0
