import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

export default function Home() {
  return (
    <div className="space-y-8">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-bold tracking-tight">
          Welcome to <span className="text-primary">PROJECT_NAME</span>
        </h1>
        <p className="text-xl text-muted-foreground">
          A modern Next.js full-stack application generated by OpenClaw Scaffolding Engine
        </p>
        <div className="flex justify-center space-x-2">
          <Badge variant="outline">Next.js 14+</Badge>
          <Badge variant="outline">TypeScript</Badge>
          <Badge variant="outline">Tailwind CSS</Badge>
          <Badge variant="outline">App Router</Badge>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>🚀 Production Ready</CardTitle>
            <CardDescription>Built with best practices</CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              <li>• Type-safe with TypeScript</li>
              <li>• Optimized for performance</li>
              <li>• SEO-friendly structure</li>
              <li>• Responsive design</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>🔧 Developer Experience</CardTitle>
            <CardDescription>Tools included</CardDescription>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              <li>• ESLint + Prettier</li>
              <li>• Husky git hooks</li>
              <li>• Vitest for unit testing</li>
              <li>• Playwright for E2E</li>
            </ul>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>⚡ Quick Start</CardTitle>
            <CardDescription>Get started immediately</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <code className="block bg-muted p-2 rounded text-sm">npm run dev</code>
              <p className="text-sm text-muted-foreground">Start development server</p>
            </div>
            <div className="space-y-2">
              <code className="block bg-muted p-2 rounded text-sm">npm run build</code>
              <p className="text-sm text-muted-foreground">Build for production</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>📁 Project Structure</CardTitle>
          <CardDescription>Organized for scalability</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="bg-muted p-4 rounded-lg font-mono text-sm">
            <div>PROJECT_NAME/</div>
            <div className="ml-4">├── src/</div>
            <div className="ml-8">├── app/ <span className="text-muted-foreground"># App Router pages</span></div>
            <div className="ml-8">├── components/ <span className="text-muted-foreground"># Reusable components</span></div>
            <div className="ml-8">├── lib/ <span className="text-muted-foreground"># Utilities & helpers</span></div>
            <div className="ml-8">└── types/ <span className="text-muted-foreground"># TypeScript types</span></div>
            <div className="ml-4">├── public/ <span className="text-muted-foreground"># Static assets</span></div>
            <div className="ml-4">└── tests/ <span className="text-muted-foreground"># Test files</span></div>
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-center space-x-4">
        <Button size="lg">Get Started</Button>
        <Button size="lg" variant="outline">View Documentation</Button>
        <Button size="lg" variant="outline">API Reference</Button>
      </div>
    </div>
  )
}