#!/bin/bash
#
# GitHub Push Script - Phase 3
# Automates git init, repo creation, and push to GitHub
#

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }

# Configuration
GITHUB_TOKEN="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
GITHUB_USERNAME="${GITHUB_USERNAME:-}"
DEFAULT_VISIBILITY="${GITHUB_REPO_VISIBILITY:-public}"

# Help message
show_help() {
    cat << 'HELP'
Usage: github-push.sh [OPTIONS] <project-path> [repo-name]

Automates git initialization, GitHub repository creation, and push.

Arguments:
  project-path    Path to the project directory to push
  repo-name       Name for the GitHub repository (optional, defaults to project folder name)

Options:
  --private       Create a private repository (default: public)
  --public        Create a public repository (default)
  --dry-run       Show what would be done without executing
  --description   Repository description (default: auto-generated)
  --help          Show this help message

Environment Variables:
  GITHUB_TOKEN    GitHub personal access token (required)
  GITHUB_USERNAME GitHub username (optional, auto-detected)

Examples:
  github-push.sh ./my-app
  github-push.sh --private ./my-app my-custom-repo-name
  GITHUB_TOKEN=xxx github-push.sh ./my-app

HELP
}

# Parse arguments
PROJECT_PATH=""
REPO_NAME=""
VISIBILITY="$DEFAULT_VISIBILITY"
DRY_RUN=false
DESCRIPTION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --private)
            VISIBILITY="private"
            shift
            ;;
        --public)
            VISIBILITY="public"
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --description)
            DESCRIPTION="$2"
            shift 2
            ;;
        --help)
            show_help
            exit 0
            ;;
        -*)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
        *)
            if [[ -z "$PROJECT_PATH" ]]; then
                PROJECT_PATH="$1"
            elif [[ -z "$REPO_NAME" ]]; then
                REPO_NAME="$1"
            else
                log_error "Too many arguments"
                show_help
                exit 1
            fi
            shift
            ;;
    esac
done

# Validate required arguments
if [[ -z "$PROJECT_PATH" ]]; then
    log_error "Project path is required"
    show_help
    exit 1
fi

# Resolve project path to absolute path
PROJECT_PATH="$(cd "$PROJECT_PATH" 2>/dev/null && pwd)" || {
    log_error "Project path does not exist: $PROJECT_PATH"
    exit 1
}

# Auto-detect repo name from project path if not provided
if [[ -z "$REPO_NAME" ]]; then
    REPO_NAME="$(basename "$PROJECT_PATH")"
fi

# Auto-generate description if not provided
if [[ -z "$DESCRIPTION" ]]; then
    DESCRIPTION="Project generated by OpenClaw Scaffolding Engine"
fi

log_info "GitHub Push Automation"
log_info "======================="
log_info "Project: $PROJECT_PATH"
log_info "Repository: $REPO_NAME"
log_info "Visibility: $VISIBILITY"
if [[ "$DRY_RUN" == true ]]; then
    log_warn "DRY RUN MODE - No changes will be made"
fi
echo ""

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check for git
    if ! command -v git &> /dev/null; then
        log_error "git is not installed"
        return 1
    fi
    
    # Check for curl
    if ! command -v curl &> /dev/null; then
        log_error "curl is not installed"
        return 1
    fi
    
    # Check for GitHub token
    if [[ -z "$GITHUB_TOKEN" ]]; then
        log_error "GITHUB_TOKEN environment variable is not set"
        log_info "Get a token at: https://github.com/settings/tokens"
        log_info "Required scopes: repo"
        return 1
    fi
    
    # Get GitHub username if not set
    if [[ -z "$GITHUB_USERNAME" ]]; then
        log_info "Detecting GitHub username..."
        GITHUB_USERNAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/user | grep -o '"login": "[^"]*"' | cut -d'"' -f4)
        
        if [[ -z "$GITHUB_USERNAME" ]]; then
            log_error "Could not detect GitHub username"
            log_info "Set GITHUB_USERNAME environment variable manually"
            return 1
        fi
        log_success "GitHub username: $GITHUB_USERNAME"
    fi
    
    log_success "Prerequisites check passed"
    return 0
}

# Initialize git repository
init_git() {
    log_info "Initializing git repository..."
    
    cd "$PROJECT_PATH"
    
    if [[ -d ".git" ]]; then
        log_warn "Git repository already initialized"
        return 0
    fi
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would run: git init"
        return 0
    fi
    
    if git init; then
        log_success "Git repository initialized"
    else
        log_error "Failed to initialize git repository"
        return 1
    fi
    
    return 0
}

# Configure git user (if not already set)
configure_git() {
    log_info "Configuring git user..."
    
    cd "$PROJECT_PATH"
    
    # Check if git user is configured
    local git_name=$(git config user.name 2>/dev/null || echo "")
    local git_email=$(git config user.email 2>/dev/null || echo "")
    
    if [[ -z "$git_name" ]]; then
        if [[ "$DRY_RUN" == true ]]; then
            log_info "[DRY-RUN] Would set git user.name"
        else
            git config user.name "OpenClaw Scaffolder"
            log_info "Set git user.name: OpenClaw Scaffolder"
        fi
    fi
    
    if [[ -z "$git_email" ]]; then
        if [[ "$DRY_RUN" == true ]]; then
            log_info "[DRY-RUN] Would set git user.email"
        else
            git config user.email "scaffolder@openclaw.local"
            log_info "Set git user.email: scaffolder@openclaw.local"
        fi
    fi
    
    return 0
}

# Create GitHub repository via API
create_github_repo() {
    log_info "Creating GitHub repository: $REPO_NAME"
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would create GitHub repo: $REPO_NAME ($VISIBILITY)"
        return 0
    fi
    
    # Check if repo already exists
    local existing_repo=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/repos/$GITHUB_USERNAME/$REPO_NAME" | grep -o '"id":' || echo "")
    
    if [[ -n "$existing_repo" ]]; then
        log_warn "Repository $REPO_NAME already exists"
        log_info "Will push to existing repository"
        return 0
    fi
    
    # Create repository
    local response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -X POST \
        -d "{\"name\":\"$REPO_NAME\",\"description\":\"$DESCRIPTION\",\"private\":$(if [[ "$VISIBILITY" == "private" ]]; then echo "true"; else echo "false"; fi),\"auto_init\":false}" \
        https://api.github.com/user/repos)
    
    # Check for errors
    if echo "$response" | grep -q '"message":'; then
        local error_msg=$(echo "$response" | grep -o '"message": "[^"]*"' | cut -d'"' -f4)
        log_error "Failed to create repository: $error_msg"
        return 1
    fi
    
    # Check if repo was created
    if echo "$response" | grep -q '"html_url":'; then
        local repo_url=$(echo "$response" | grep -o '"html_url": "[^"]*"' | head -1 | cut -d'"' -f4)
        log_success "Repository created: $repo_url"
    else
        log_error "Failed to create repository (unexpected response)"
        return 1
    fi
    
    return 0
}

# Add remote and push
push_to_github() {
    log_info "Pushing to GitHub..."
    
    cd "$PROJECT_PATH"
    
    local repo_url="https://github.com/$GITHUB_USERNAME/$REPO_NAME.git"
    
    # Check if remote already exists
    if git remote get-url origin &>/dev/null; then
        log_warn "Remote 'origin' already exists"
        if [[ "$DRY_RUN" != true ]]; then
            git remote set-url origin "$repo_url"
            log_info "Updated remote URL"
        fi
    else
        if [[ "$DRY_RUN" == true ]]; then
            log_info "[DRY-RUN] Would add remote: origin $repo_url"
        else
            git remote add origin "$repo_url"
            log_success "Added remote: origin"
        fi
    fi
    
    # Check if there are files to commit
    if [[ -n $(git status --porcelain) ]]; then
        if [[ "$DRY_RUN" == true ]]; then
            log_info "[DRY-RUN] Would add and commit all files"
        else
            git add .
            git commit -m "Initial commit via OpenClaw Scaffolding Engine

- Project generated from template
- TypeScript, ESLint, and Prettier configured
- Ready for development" || {
                log_warn "Nothing to commit or commit failed"
            }
        fi
    else
        log_warn "No changes to commit"
    fi
    
    # Push to GitHub
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would push to origin main"
    else
        # Try main branch first, then master
        if git push -u origin main 2>/dev/null; then
            log_success "Pushed to origin main"
        elif git push -u origin master 2>/dev/null; then
            log_success "Pushed to origin master"
        else
            log_error "Failed to push to GitHub"
            log_info "You may need to push manually:"
            log_info "  cd $PROJECT_PATH"
            log_info "  git push -u origin main"
            return 1
        fi
    fi
    
    return 0
}

# Main execution
main() {
    # Check prerequisites
    if ! check_prerequisites; then
        exit 1
    fi
    
    # Initialize git
    if ! init_git; then
        exit 1
    fi
    
    # Configure git
    configure_git
    
    # Create GitHub repository
    if ! create_github_repo; then
        exit 1
    fi
    
    # Push to GitHub
    if ! push_to_github; then
        exit 1
    fi
    
    # Success output
    echo ""
    log_success "GitHub push completed successfully!"
    echo ""
    echo -e "${GREEN}Repository URL:${NC} https://github.com/$GITHUB_USERNAME/$REPO_NAME"
    echo -e "${GREEN}Local Path:${NC} $PROJECT_PATH"
    echo ""
    
    return 0
}

# Run main function
main
exit $?
